### ISSUE TITLE
Sapper integration 

### ISSUE THREAD

**Issue by rob-balfre** [TehShrike/svelte-preprocess-postcss#3]
Spent a while this afternoon trying to get svelte-preprocess-postcss working with Sapper. Not managed to get it working yet - any pointers?

**Comment by TehShrike** [comment]
I dunno, sounds like a Sapper deal - tried looking for some Sapper issues? https://github.com/sveltejs/sapper/issues/213#issuecomment-375021835

**Comment by rob-balfre** [comment]
I had created a postcss.config.js file at the root of the sapper project and presumed svelte-preprocess-postcss was picking it up, it wasn't so just updated the webpack configs to:
 `style: stylePreprocessor({
              useConfigFile: false,
              plugins: [
                require('precss')
              ]
            })`

Working now.  Thanks.
