### ISSUE TITLE
Deprecate the package in favour of "svelte-preprocess"

### ISSUE THREAD

**Issue by artemjackson** [TehShrike/svelte-preprocess-postcss#7]
https://github.com/kaisermann/svelte-preprocess already solved the package goal

**Comment by TehShrike** [comment]
"already solved'?  This library predates svelte-preprocess.

If you want PostCSS preprocessing, svelte-preprocess is the wrong tool for the job.  It does more than you need.

I would recommend using libraries that solve your specific problem - don't use libraries that try to do too much.
